apiVersion: v1
kind: PersistentVolume
metadata:
  name: datascience-model-mesh-pv
  labels:
    type: local-shared-storage
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi              # Espacio elástico asignado para almacenar múltiples grafos de ONNX
  accessModes:
    - ReadWriteMany            # Patrón crítico: Permite que múltiples Pods lean y Airflow escriba al mismo tiempo
  hostPath:
    path: "/Users/edithbg/PoC/DataScience/inference-engine/models" # Ruta física espejo en tu Mac para desarrollo local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datascience-model-mesh-pvc
  namespace: datascience-production
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany            # Debe coincidir exactamente con los permisos del PersistentVolume
  resources:
    requests:
      storage: 5Gi             # Volumen de cuota solicitado por el deployment del microservicio
